// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCobwj19Yawpbc8PXDGqiM-qnvPrXFdtNY',
    appId: '1:525665813230:web:bc9e77afde3c6b50ae29ff',
    messagingSenderId: '525665813230',
    projectId: 'fir-chat-9bd81',
    authDomain: 'fir-chat-9bd81.firebaseapp.com',
    storageBucket: 'fir-chat-9bd81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyqgccQZwg4RQC-V5xG0lkZ1SQdvoArbc',
    appId: '1:525665813230:android:519b4df6694707ceae29ff',
    messagingSenderId: '525665813230',
    projectId: 'fir-chat-9bd81',
    storageBucket: 'fir-chat-9bd81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMlxTI99p48lxwY0c_Kh99eXE7zdANmdk',
    appId: '1:525665813230:ios:bfc6a90e04ab8caeae29ff',
    messagingSenderId: '525665813230',
    projectId: 'fir-chat-9bd81',
    storageBucket: 'fir-chat-9bd81.appspot.com',
    iosClientId: '525665813230-73og6gaqi4ffugvk4osultmpdo2t57oh.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseChat',
  );
}
